name = "CTParser"
uuid = "32681960-a1b1-40db-9bff-a1ca817385d1"
version = "0.8.2-beta.4"
authors = ["Jean-Baptiste Caillau <jean-baptiste.caillau@univ-cotedazur.fr>"]

[deps]
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ExaModels = "1037b233-b668-4ce9-9b63-f9f681f55dd2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
CTBase = "0.16, 0.17"
DocStringExtensions = "0.9"
ExaModels = "0.9.3"
MLStyle = "0.4"
OrderedCollections = "1"
Parameters = "0.12"
Unicode = "1"
julia = "1.10"
